Title = "SaraSortd Config"
SafeMode = 1
SilentMode = 0
CheckInput = 10
OutputDir = [ "Log",]

[Variables]
NextNum = "*"
NextChar = "&"
Parent = "@"
OrgFileName = "~"
OrgFileType = "^"
Year = "[y]"
Month = "[m]"
Day = "[d]"
Hour = "[h]"
Minute = "[n]"
Second = "[s]"
VarCall = "%%"

[DirectoryPaths]
RootDir = "/home/sarah/TESTDIR"
InputDir = [ "%RootDir%",]
OutputDir = [ "%RootDir%/Output",]
LogDir = "%RootDir%/.Logs"
FailedDir = "%RootDir%/.Failed"

[Names]
LogFileName = "[y].[m].[d]._*"
DirConfName = ".@Config"

[Log]
All = "[h]:[n]:[s] | "
Start = "Started: SaraSortd"
NotStart = "Error: Failed to start SaraSortd."
Sorted = "Sorted: %% to %%."
ValueSet = "Set: %% to be %% in %%."
WrongType = "Error: %% is not a %%."
Unset = "Error: %% is not set."