Title = "SaraSortd Config"
SafeMode = 1
SilentMode = 0
CheckInput = 3
DotFiles = 0

[Variables]
NextNum = "!"
NextChar = "&"
Parent = "@"
OrgFileName = "~"
OrgFileType = "^"
Year = "[y]"
Month = "[m]"
Day = "[d]"
Hour = "[h]"
Minute = "[n]"
Second = "[s]"
VarCall = "%%"

[DirectoryPaths]
RootDir = "Unset"
InputDir = [ "%RootDir%"]
OutputDir = [ "%RootDir%/Output"]
LogDir = "%RootDir%/.Logs"
FailedDir = "%RootDir%/.Failed"

[Names]
LogFileName = "[y].[m].[d]"
DirConfName = ".@Config"

[Log]
All = "[h]:[n]:[s] | "
Start = "Started SaraSortd."
NotStart = "Error: Failed to start SaraSortd."
MatchPattern = "Checking %%."
Sorted = "Sorted %%."
NotSorted = "Error: Failed to sort %%. No valid output directory."
ValueSet = "Set %%."
Unset = "Error: %% is not set."
